### ISSUE TITLE
Investigate build failures on Travis

### ISSUE THREAD

**Issue by urdh** [urdh/eu4-parser#15]
Log except:
```
In file included from libeu4parser/src/bitmap.cpp:2:
/home/travis/build/urdh/eu4-parser/libeu4parser/include/exceptions.hpp:7:22: error: no member named 'literals' in namespace 'std'
using namespace std::literals::string_literals;
                ~~~~~^
/home/travis/build/urdh/eu4-parser/libeu4parser/include/exceptions.hpp:7:32: error: expected namespace name
using namespace std::literals::string_literals;
                               ^
/home/travis/build/urdh/eu4-parser/libeu4parser/include/exceptions.hpp:15:28: error: no matching literal operator for call to 'operator "" s' with arguments of types 'const char *' and 'unsigned long', and no matching literal operator template
        ("BMP read error: "s + error)
```

Builds just fine using newer Clang from Xcode. Possibly GCC X.Y should be allowed to fail, but Clang should work properly (unless it's a known defect somewhere).

**Comment by urdh** [comment]
Hints may be given by https://cplusplusmusings.wordpress.com/2012/07/05/clang-and-standard-libraries-on-mac-os-x/

**Comment by urdh** [comment]
It's the lack of `libc++`, but since the Ubuntu version used by Travis is old and doesn't provide packages this has to be dropped for now. Ideally Travis works on getting Ubuntu 14.04 and clang-3.5 with libc++ (and gcc-4.8 or something).

**Comment by urdh** [comment]
Been working a bit on this today.
